[package]
name = "augment-vip-jetbrains"
version = "0.1.1"
edition = "2021"

[dependencies]
uuid = { version = "1.4", features = ["v4"] }
dirs = "6.0.0"
base64 = "0.22"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"
